### ISSUE TITLE
requirements.txt file is missing

### ISSUE THREAD

**Issue by stalane** [kaustav202/RealTime-TwitterDataAnalysis#1]
from: Run pip install -r requirements.txt to install all the dependencies.

problem: requirements.txt file is missing from repo

**Comment by gokullan** [comment]
Hi, there! Can this issue be assigned to me?

**Comment by kaustav202** [comment]
sure.. but do check all the modules

**Comment by gokullan** [comment]
Yes, will do.

**Comment by mohantyrohan3** [comment]
Hello @stalane I have already done a pull request regarding this , Can you please assign here

**Comment by kaustav202** [comment]
> Hello @stalane I have already done a pull request regarding this , Can you please assign here

It had been already assigned so you're on standby. You can contribute to other aspects of the project.
