### ISSUE TITLE
Add tweet logger

### ISSUE THREAD

**Issue by kaustav202** [kaustav202/RealTime-TwitterDataAnalysis#14]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] change/modification
  - [ ] design issue

* **Do you want to request a *feature* or report a *bug*?**

Continuously log the number new tweets that keep being written to the tweets.json file with run of stream.py

**Comment by rexdivakar** [comment]
Hey @kaustav202 i can work on this issue, kindly assign it to my name

**Comment by kaustav202** [comment]
> Hey @kaustav202 i can work on this issue, kindly assign it to my name

I'll have to hold you on that for now as you are already assigned one. You can take this up after completing it.

**Comment by mayanksharma-1** [comment]
hey, I am participating in hacktoberfest can I work on this?

**Comment by kaustav202** [comment]
okay.. you can go ahead

**Comment by Coder-Manan** [comment]
Hi, I am ready to work on this. Please assign me this issue

**Comment by Coder-Manan** [comment]
I have raised a PR (#23 ). Please review it
