### ISSUE TITLE
Integrate sentiment_analysis.py with main

### ISSUE THREAD

**Issue by kaustav202** [kaustav202/RealTime-TwitterDataAnalysis#15]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] change/modification
  - [ ] design issue

* **Do you want to request a *feature* or report a *bug*?**

The sentiment analysis functionality needs to run as part of main ( through import )

* **What is the current behavior?**

Import in main is commented out due to error. Auxiliary module sentiment_analysis import causing error

* **What is the expected behavior?**

Generate sentiment plots without errors. Possibly create two separate functions for sentiment score generation and plot generation in
sentiment_analysis.py inside a class based and call them by importing in main.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Note : ds_twets does not need to be generated again in sentiment_analysis as it is already in main.py and also converted to time-series, so it can be utilized for time-series plotting

**Comment by segfal** [comment]
Can i work on this? i've  done something like this before, so i can try to fix the sentimental analysis part.

**Comment by kaustav202** [comment]
sure.. go ahead with it

**Comment by segfal** [comment]
Im almost done, i am just testing it right now so it doesn't create any new bugs
