### ISSUE TITLE
Improve documentation [ Set-up and Usage ]

### ISSUE THREAD

**Issue by Rishav-12** [kaustav202/RealTime-TwitterDataAnalysis#3]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] change/modification
  - [ ] design issue

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
There are a few typos/grammatical errors in the README file. Also I think if some points in the setup steps are elaborated, it will be useful to people using the project

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I think there should be some more details, especially on how to setup to use the project locally, including the Twitter API setup

* **What is the motivation / use case for changing the behavior?**
Helping people who use the project by improving the documentation in the README

* **Please tell us about your environment:**
  
  - Version: 
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Rishav-12** [comment]
Hey @kaustav202 can you please take a look at this and assign me if possible

**Comment by kaustav202** [comment]
absolutely.. I'm assigning you this issue
