### ISSUE TITLE
Doc Update [ Badges for Domain and Tech Stack ]

### ISSUE THREAD

**Issue by kaustav202** [kaustav202/RealTime-TwitterDataAnalysis#4]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] change/modification
  - [ ] design issue

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

The Domain and Tech Stack sections of the readme is currently formatted as lists which consumes a lot of space

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

If graphic labels or badges in form of svg embeds were used instead, it will be a lot more concise and small ( horizontally laid out )

* **What is the motivation / use case for changing the behavior?**

It will allow the focus of reader to be drawn on the important parts such as usage and technical aspects instead.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Some useful references 

https://github.com/alexandresanlim/Badges4-README.md-Profile

https://github.com/Naereen/badges

https://github.com/badges/shields

https://shields.io/

**Comment by bindu-r02** [comment]
@kaustav202 - Can I try this

**Comment by kaustav202** [comment]
yes go ahead !

**Comment by kaustav202** [comment]
@bindu-r02  any progress?

**Comment by jatin00000** [comment]
Hey! Can I work on this issue?

**Comment by kaustav202** [comment]
> Hey! Can I work on this issue?

sure.. i will be assigning you
